### ISSUE TITLE
Conflict between Story.AutoPlay and TwineTextPlayer.StartStory

### ISSUE THREAD

**Issue by Seminko** [daterre/Cradle#8] opened 2015-12-29 15:09 UTC
Hey man, so I did what you copy UnityTwine into the Assets, and in my 2D project dragged TwinTextPlayer prefab into the scene. I imported the *.twee file which automatically created a Csharp script which I then dragged onto the TwinTextPlayer on the left tab.

However when I press play, the screen stays black. When I stop it, and go into the Game tab, it says Twine Text and under that Twine Link.

I'm first trying with a test file to keep it simple:
:: StoryTitle
Slumber

:: UserScript[script]

:: UserStylesheet[stylesheet]

:: Start
Hovno s makem.

[[S tabakem]]
[[Bez tabaku]]

:: S tabakem
[[Stejne hovno.]]

:: Bez tabaku
[[Stejne hovno.]]

:: Stejne hovno.
You wins!

There are no issues in the debug log.

I can make screenshots / vid to show how I do it, I'm sure it's something minor.

EDIT: Ok, for some reason when I attach the story script I have to save it, close Unity and when I open it up again it works. Any idea regarding that?

**Comment by cswiatek** [comment] 2016-03-19 06:24
I ran into this problem today and in my searching saw this post with no replies. Your solution worked for some odd reason, but the kicker was that I could not build the game to an APK without incurring the same problem yet again.

I managed to solve the problem by taking a look at the Twine Text Player script attached to the TwineTextPlayer prefab (which you should be using in the scene to display your story). 

To fix it, you need to a) select the correct story script in the Story field and b) make sure that Start Story is set to true (box checked). Save your scene and that should fix it!

Note that if this box is checked on the Twine Text Player script you do not need to check the Auto Play box on your story script. Doing so will cause any hooks for the first scene to execute twice, as it technically starts the scene two times.

![image](https://cloud.githubusercontent.com/assets/5642660/13897043/a9dff4de-ed5f-11e5-9831-d68dad0cfcb2.png)

**Comment by daterre** [comment] 2016-03-23 15:38
Thanks for the feedback, and apologies I haven't addressed this issue yet.
The Twine Text Player was intended to be more of demo component than an
actual part of the system, and so could definitely use some improvements.
I'll do my best to freshen it up for new version due out by the end of the
month.

Doron Assayas Terre
interactive • storytelling • code

web: *daterre.com <http://daterre.com/>*
twitter:  @tonicwoods <https://twitter.com/tonicwoods>

<http://www.lofipeople.com/>

**Comment by daterre** [comment] 2016-08-17 14:32
This has been fixed in Cradle (UnityTwine v2) - Story.AutoPlay cannot be enabled in the editor when TwineTextPlayer.StartStory is checked.

**Closed by daterre** 2016-08-17 14:32 UTC
Labels: bug
